#pragma once

#define COMBO_COUNT 15
#define COMBO_TERM 75

#define TAP_CODE_DELAY 25

#define LEADER_TIMEOUT 300
#define LEADER_PER_KEY_TIMING

#define TAPPING_FORCE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

// These are the colors I used on my ffkb low pro ks-27 with the xvx horizon purple and green keycaps
 #define FP_LAYER_LIGHTING_HUE_2 HSV_GREEN
 #define FP_LAYER_LIGHTING_HUE_3 HSV_ORANGE
 #define FP_LAYER_LIGHTING_HUE_4 HSV_YELLOW
 #define FP_LAYER_LIGHTING_HUE_5 HSV_PURPLE
 #define FP_LAYER_LIGHTING_HUE_6 HSV_RED

 #define FP_LAYER_LIGHTING_MODE_5 RGB_MATRIX_MULTISPLASH

#define RGBLIGHT_LAYERS_RETAIN_VAL

#define OLED_DISABLE_TIMEOUT4
#ifdef RGB_MATRIX_ENABLE
  #define RGB_MATRIX_TIMEOUT 0
  #undef RGB_MATRIX_LED_COUNT
  #define RGB_MATRIX_LED_COUNT 36
  #define RGB_MATRIX_CENTER {100, 32}
  //#undef RGB_MATRIX_MAXIMUM_BRIGHTNESS
  //#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200 /* 112 The maximum brightness level for RGB_MATRIX */
  #define RGB_MATRIX_STARTUP_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS // Sets the default brightness value, if none has been set
  #define RGB_MATRIX_KEYPRESSES
  #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
  #define RGB_MATRIX_KEYREACTIVE_ENABLED
  #define ENABLE_RGB_MATRIX_ALPHAS_MODS
  #undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
  #undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
  #undef ENABLE_RGB_MATRIX_BREATHING
  #undef ENABLE_RGB_MATRIX_BAND_SAT
  #undef ENABLE_RGB_MATRIX_BAND_VAL
  #undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
  #undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
  #undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
  #undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
  #undef ENABLE_RGB_MATRIX_CYCLE_ALL
  #undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
  #undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
  #undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
  #undef ENABLE_RGB_MATRIX_DUAL_BEACON
  #undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
  #undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
  #undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
  #undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
  #undef ENABLE_RGB_MATRIX_RAINDROPS
  #undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
  #undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
  #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
  #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
  #undef ENABLE_RGB_MATRIX_SPLASH
  #define ENABLE_RGB_MATRIX_MULTISPLASH
  #undef ENABLE_RGB_MATRIX_SOLID_SPLASH
  #undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
  #undef RGBLIGHT_MODE_SNAKE
#endif
